# Generated by Django 4.1.9 on 2023-07-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_member"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sermon",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("date", models.DateField()),
                ("speaker", models.CharField(max_length=100)),
                ("file", models.FileField(upload_to="sermons/")),
            ],
        ),
    ]
