# Generated by Django 4.1.9 on 2023-07-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_sermon"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("members", models.ManyToManyField(related_name="group_memberships", to="users.member")),
            ],
        ),
    ]
